Repository polkadot-developers/polkadot-docs, pull requests merged in 2024-12, with the labels that each got.

#221 Tutorials > Interoperability > XCM Transfers
  .snippets/code/tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain/output.html
  .snippets/code/tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain/reserve-backed-transfer.js
  images/tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain/from-relaychain-to-parachain-01.webp
  images/tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain/from-relaychain-to-parachain-02.webp
  images/tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain/from-relaychain-to-parachain-03.webp
  images/tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain/from-relaychain-to-parachain-04.webp
  images/tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain/from-relaychain-to-parachain-05.webp
  images/tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain/from-relaychain-to-parachain-06.webp
  images/tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain/from-relaychain-to-parachain-07.webp
  tutorials/interoperability/.pages
  tutorials/interoperability/xcm-transfers/.pages
  tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain.md
  tutorials/interoperability/xcm-transfers/index.md
Labels: Pre-Launch, HIGH

#230 [FIX] - Adding references to tutorials
  develop/interoperability/xcm-channels.md
  develop/parachains/customize-parachain/add-existing-pallets.md
  develop/parachains/customize-parachain/add-smart-contract-functionality.md
  develop/parachains/customize-parachain/make-custom-pallet.md
  develop/parachains/customize-parachain/pallet-testing.md
  develop/parachains/deployment/generate-chain-specs.md
  develop/parachains/get-started/build-custom-parachains.md
  develop/parachains/get-started/deploy-parachain-to-polkadot.md
  develop/parachains/maintenance/runtime-upgrades.md
  develop/parachains/testing/setup.md
  develop/toolkit/parachains/fork-chains/chopsticks/get-started.md
  develop/toolkit/parachains/spawn-chains/zombienet/get-started.md
  polkadot-protocol/architecture/parachains/consensus.md
  polkadot-protocol/architecture/parachains/overview.md
  polkadot-protocol/architecture/system-chains/asset-hub.md
Labels: Pre-Launch, HIGH

#233 Tutorials > Polkadot SDK > Parachains > Build Custom Pallet > Pallet Unit Testing
  .husky/pre-commit
  .snippets/code/tutorials/polkadot-sdk/parachains/build-custom-pallet/build-pallet/Cargo.toml
  .snippets/code/tutorials/polkadot-sdk/parachains/build-custom-pallet/build-pallet/call_structure.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/build-custom-pallet/build-pallet/compilation-output.html
  .snippets/code/tutorials/polkadot-sdk/parachains/build-custom-pallet/build-pallet/lib.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/build-custom-pallet/build-pallet/scaffold.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/build-custom-pallet/pallet-unit-testing/Cargo-dev-dependencies.toml
  .snippets/code/tutorials/polkadot-sdk/parachains/build-custom-pallet/pallet-unit-testing/mock.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/build-custom-pallet/pallet-unit-testing/output.html
  .snippets/code/tutorials/polkadot-sdk/parachains/build-custom-pallet/pallet-unit-testing/pallet-calls.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/build-custom-pallet/pallet-unit-testing/tests.rs
  tutorials/polkadot-sdk/parachains/build-custom-pallet/.pages
  tutorials/polkadot-sdk/parachains/build-custom-pallet/build-pallet.md
  tutorials/polkadot-sdk/parachains/build-custom-pallet/pallet-unit-testing.md
Labels: Pre-Launch, HIGH

#234 Tutorials: Update parachain tutorial
  .snippets/code/tutorials/polkadot-sdk/parachains/connect-to-relay-chain/acquire-a-testnet-slot/acquire-a-testnet-slot-2.html
  .snippets/code/tutorials/polkadot-sdk/parachains/connect-to-relay-chain/acquire-a-testnet-slot/deploy-on-paseo-3.html
  .snippets/code/tutorials/polkadot-sdk/parachains/connect-to-relay-chain/prepare-parachain/prepare-parachain-3.html
  .snippets/code/tutorials/polkadot-sdk/parachains/connect-to-relay-chain/prepare-parachain/prepare-parachain-4.html
  .snippets/code/tutorials/polkadot-sdk/parachains/connect-to-relay-chain/prepare-parachain/prepare-parachain-5.html
  images/tutorials/polkadot-sdk/parachains/connect-to-relay-chain/acquire-a-testnet-slot/acquire-a-testnet-slot-10.webp
  images/tutorials/polkadot-sdk/parachains/connect-to-relay-chain/acquire-a-testnet-slot/acquire-a-testnet-slot-9.webp
  tutorials/polkadot-sdk/parachains/.pages
  tutorials/polkadot-sdk/parachains/connect-to-relay-chain/.pages
  tutorials/polkadot-sdk/parachains/connect-to-relay-chain/prepare-parachain.md
  tutorials/polkadot-sdk/parachains/connect-to-relay-chain/prepare-relay-chain.md
  tutorials/polkadot-sdk/parachains/deploy-to-relay-chain/.pages
  tutorials/polkadot-sdk/parachains/deploy-to-relay-chain/deploy-on-paseo.md
  tutorials/polkadot-sdk/parachains/deploy-to-relay-chain/index.md
Labels: Ready for Review

#250 Obtain Coretime Tutorial
  .snippets/code/tutorials/polkadot-sdk/parachains/obtain-coretime/obtain-coretime-1.html
  images/tutorials/polkadot-sdk/parachains/obtain-coretime/obtain-coretime-1.webp
  images/tutorials/polkadot-sdk/parachains/obtain-coretime/obtain-coretime-10.webp
  images/tutorials/polkadot-sdk/parachains/obtain-coretime/obtain-coretime-2.webp
  images/tutorials/polkadot-sdk/parachains/obtain-coretime/obtain-coretime-3.webp
  images/tutorials/polkadot-sdk/parachains/obtain-coretime/obtain-coretime-4.webp
  images/tutorials/polkadot-sdk/parachains/obtain-coretime/obtain-coretime-5.webp
  images/tutorials/polkadot-sdk/parachains/obtain-coretime/obtain-coretime-6.webp
  images/tutorials/polkadot-sdk/parachains/obtain-coretime/obtain-coretime-7.webp
  images/tutorials/polkadot-sdk/parachains/obtain-coretime/obtain-coretime-8.webp
  images/tutorials/polkadot-sdk/parachains/obtain-coretime/obtain-coretime-9.webp
  tutorials/polkadot-sdk/parachains/.pages
  tutorials/polkadot-sdk/parachains/obtain-coretime.md
Labels: Ready for Review

#249 Merge dev-pathways into develop/index
  develop/.pages
  develop/development-pathways.md
  develop/index.md
  develop/parachains/index.md
  develop/smart-contracts/index.md
  develop/toolkit/index.md
  develop/toolkit/integrations/wallets.md
Labels: Pre-Launch, HIGH

#267 Create mermaid diagram for Substrate Node
  develop/parachains/intro-polkadot-sdk.md
Labels: documentation
