Repository polkadot-developers/polkadot-docs, pull requests merged in 2024-11, with the labels that each got.

#111 Develop > Testing > Setup
  .snippets/code/develop/blockchains/testing/setup/genesis-config-custom.rs
  .snippets/code/develop/blockchains/testing/setup/genesis-config.rs
  .snippets/code/develop/blockchains/testing/setup/integration-testing-module.rs
  develop/blockchains/testing/setup.md
Labels: Ready for Review

#26 [Substrate.io] Deterministic Runtime
  .snippets/code/develop/parachain-devs/runtime-development/build-deterministic-runtime/deterministic-runtime-1.html
  develop/blockchains/deployment/.pages
  develop/blockchains/deployment/build-deterministic-runtime.md
  variables.yml
Labels: Ready for Review

#116 Develop > Testing > Runtime
  .snippets/code/develop/blockchains/testing/runtime/full-integration-test.rs
  .snippets/code/develop/blockchains/testing/runtime/pallet-a-integration-test.rs
  .snippets/code/develop/blockchains/testing/runtime/pallet-b-call.rs
  .snippets/code/develop/blockchains/testing/runtime/pallet-b-integration-test.rs
  .snippets/code/develop/blockchains/testing/runtime/pallet-coupling.rs
  develop/blockchains/testing/runtime.md
Labels: Ready for Review

#113 Polkadot Protocol > Basics > Randomness
  images/polkadot-protocol/basics/blocks-transactions-fees/randomness/slots-epochs.webp
  polkadot-protocol/basics/randomness.md
Labels: Ready for Review, Polkadot Protocol

#129 Build > Blockchains > Get Started > Deploy a Blockchain to Polkadot
  develop/blockchains/deployment/overview.md
  develop/blockchains/get-started/deploy-blockchain-to-polkadot.md
Labels: Ready for Review

#27 [Substrate.io] Chain Specification
  .snippets/code/develop/blockchains/deployment/generate-chain-specs/basic-chain-specs.json
  .vscode/settings.json
  develop/blockchains/deployment/.pages
  develop/blockchains/deployment/generate-chain-specs.md
  develop/parachain-devs/parachain-launch/.pages
  develop/smart-contracts/chain-spec.md
Labels: Ready for Review

#115 Polkadot Protocol > Architecture > Polkadot Chain > Overview
  images/polkadot-protocol/architecture/polkadot-chain/overview/overview-1.webp
  polkadot-protocol/architecture/polkadot-chain/overview.md
Labels: Ready for Review, Polkadot Protocol

#121 Custom Blockchains > Benchmarking
  .snippets/code/develop/blockchains/custom-blockchains/benchmarking/benchmark-output.html
  .snippets/code/develop/blockchains/custom-blockchains/benchmarking/cargo.toml
  .snippets/code/develop/blockchains/custom-blockchains/benchmarking/dispatchable-pallet-weight.rs
  .snippets/code/develop/blockchains/custom-blockchains/benchmarking/frame-benchmark-macro.rs
  .snippets/code/develop/blockchains/custom-blockchains/benchmarking/weight-config.rs
  develop/blockchains/custom-blockchains/.pages
  develop/blockchains/custom-blockchains/benchmarking.md
Labels: Ready for Review

#130 Polkadot Protocol > Architecture > System Chains > Coretime
  polkadot-protocol/architecture/system-chains/coretime.md
  polkadot-protocol/glossary.md
Labels: Ready for Review

#43 [Polkadot Wiki Migration] Offenses and Slashes
  infrastructure/staking-mechanics/offenses-and-slashes.md
Labels: Ready for Review, Infrastructure

#178 Polkadot Protocol > On-Chain Governance > Origins & Tracks
  polkadot-protocol/.pages
  polkadot-protocol/onchain-governance/.pages
  polkadot-protocol/onchain-governance/origins-tracks.md
  polkadot-protocol/onchain-governance/overview.md
Labels: Ready for Review, Polkadot Protocol

#173 Develop > Smart Contracts > Native EVM contracts
  .snippets/code/develop/smart-contracts/native-evm-contracts/ether-js-browser-connection.js
  .snippets/code/develop/smart-contracts/native-evm-contracts/ether-js-server-connection.js
  develop/blockchains/custom-blockchains/frame-overview.md
  develop/smart-contracts/.pages
  develop/smart-contracts/evm/native-evm-contracts.md
  develop/smart-contracts/wasm-ink.md
  develop/smart-contracts/wasm-ink/.pages
  develop/smart-contracts/wasm-ink/index.md
  images/develop/smart-contracts/native-evm-contracts/native-evm-contracts-1.webp
  images/develop/smart-contracts/native-evm-contracts/native-evm-contracts-2.webp
Labels: Ready for Review

#172 [Polkadot Wiki Migration] Agile Coretime
  polkadot-protocol/architecture/polkadot-chain/.pages
  polkadot-protocol/architecture/polkadot-chain/agile-coretime.md
Labels: In Progress

#174 Develop > Smart Contracts > Overview
  develop/smart-contracts/overview.md
Labels: Ready for Review

#45 [Polkadot Wiki Migration] How to Validate (Polkadot)
  .snippets/code/infrastructure/running-a-node/setup-full-node/run-node.md
  .snippets/code/infrastructure/running-a-node/setup-full-node/setup-full-node-1.html
  .snippets/code/infrastructure/running-a-node/setup-full-node/setup-full-node-2.html
  .snippets/code/infrastructure/running-a-validator/onboarding-and-offboarding/set-up-a-validator/node-key-error-01.html
  .snippets/code/infrastructure/running-a-validator/onboarding-and-offboarding/set-up-a-validator/terminal-output-01.html
  .snippets/code/infrastructure/running-a-validator/onboarding-and-offboarding/set-up-a-validator/terminal-output-02.html
  .snippets/code/infrastructure/running-a-validator/operational-tasks/general-management/alertmanager-status.html
  .snippets/code/infrastructure/running-a-validator/operational-tasks/general-management/alertmanager.yml
  .snippets/code/infrastructure/running-a-validator/operational-tasks/general-management/grub-config-01.js
  .snippets/code/infrastructure/running-a-validator/operational-tasks/general-management/instance-down.yml
  .snippets/code/infrastructure/running-a-validator/operational-tasks/general-management/prometheus-config.yml
  .snippets/code/infrastructure/running-a-validator/operational-tasks/general-management/systemd-alert-config.md
  .snippets/code/infrastructure/running-a-validator/operational-tasks/general-management/systemd-config.md
  .snippets/code/infrastructure/running-a-validator/operational-tasks/general-management/terminal-output-01.html
  .snippets/code/infrastructure/running-a-validator/operational-tasks/general-management/update-prometheus.yml
  images/infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator/set-up-a-validator-01.webp
  images/infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator/set-up-a-validator-02.webp
  images/infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator/set-up-a-validator-03.webp
  images/infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator/set-up-a-validator-04.webp
  images/infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator/set-up-a-validator-05.webp
  images/infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator/set-up-a-validator-06.webp
  images/infrastructure/running-a-validator/operational-tasks/general-management/general-management-1.webp
  images/infrastructure/running-a-validator/operational-tasks/general-management/general-management-2.webp
  images/infrastructure/running-a-validator/operational-tasks/general-management/general-management-3.webp
  images/infrastructure/running-a-validator/operational-tasks/general-management/general-management-4.webp
  images/infrastructure/running-a-validator/operational-tasks/general-management/general-management-5.webp
  infrastructure/running-a-node/setup-full-node.md
  infrastructure/running-a-validator/.pages
  infrastructure/running-a-validator/onboarding-and-offboarding/.pages
  infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator.md
  infrastructure/running-a-validator/onboarding-and-offboarding/stop-validating.md
  infrastructure/running-a-validator/operational-tasks/.pages
  infrastructure/running-a-validator/operational-tasks/general-management.md
  infrastructure/running-a-validator/operational-tasks/upgrade-your-node.md
  infrastructure/running-a-validator/requirements.md
Labels: In Progress, Infrastructure

#157 Polkadot Protocol > Architecture > Parachains > Overview
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/overview/localParachainTx.ts
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/overview/paraToPara.ts
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/overview/relayToSystem.ts
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/overview/setup.ts
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/ca-example-request.ts
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/ctt-example-request.ts
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/de-example-request.ts
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/ffi-example-request.ts
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/format.ts
  polkadot-protocol/architecture/.pages
  polkadot-protocol/architecture/parachains/.pages
  polkadot-protocol/architecture/parachains/index.md
  polkadot-protocol/architecture/parachains/overview.md
Labels: In Progress

#182 Interoperability > Testing and Debugging
  develop/interoperability/.pages
  develop/interoperability/test-and-debug.md
Labels: Ready for Review

#184 Polkadot Protocol > Architecture > Parachains > Consensus
  polkadot-protocol/architecture/parachains/.pages
  polkadot-protocol/architecture/parachains/consensus.md
  polkadot-protocol/architecture/parachains/index.md
Labels: In Progress
