Repository polkadot-developers/polkadot-docs, pull requests merged in 2025-06, with the labels that each got.

#675 [FIX] - hardhat tutorial
  llms.txt
  tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#678 [FIX] - Quick fixes before SC launch
  .snippets/text/smart-contracts/code-size.md
  develop/smart-contracts/dev-environments/hardhat.md
  develop/smart-contracts/dev-environments/remix.md
  develop/smart-contracts/libraries/ethers-js.md
  develop/smart-contracts/libraries/viem.md
  develop/smart-contracts/libraries/web3-js.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#681 Migrate Westend to Passet Hub
  .snippets/code/develop/smart-contracts/dev-environments/hardhat/binary-hardhat.config.js
  .snippets/code/develop/smart-contracts/dev-environments/hardhat/hardhat.config.js
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/checkStorage.js
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/deploy.js
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/fetchLastBlock.js
  .snippets/code/develop/smart-contracts/evm-toolkit/libraries/web3-js/fetchLastBlock.js
  .snippets/code/develop/smart-contracts/libraries/viem/fetchLastBlock.ts
  .snippets/code/develop/smart-contracts/libraries/wagmi/wagmi-testnet.ts
  .snippets/code/develop/smart-contracts/libraries/web3-py/fetch_last_block.py
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/interact-output.html
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/local-deployment-output.html
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/passet-deployment-output.html
  develop/smart-contracts/block-explorers/.pages
  develop/smart-contracts/block-explorers/contract-verification.md
  develop/smart-contracts/block-explorers/index.md
  develop/smart-contracts/connect-to-polkadot.md
  develop/smart-contracts/dev-environments/hardhat.md
  develop/smart-contracts/dev-environments/remix.md
  develop/smart-contracts/faqs.md
  develop/smart-contracts/json-rpc-apis.md
  develop/smart-contracts/libraries/ethers-js.md
  develop/smart-contracts/libraries/wagmi.md
  develop/smart-contracts/libraries/web3-js.md
  develop/smart-contracts/libraries/web3-py.md
  develop/smart-contracts/wallets.md
  images/develop/smart-contracts/block-explorers/block-explorers-2.webp
  images/develop/smart-contracts/connect-to-polkadot/connect-to-polkadot-1.webp
  images/develop/smart-contracts/connect-to-polkadot/connect-to-polkadot-2.webp
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-2.webp
  images/develop/smart-contracts/wallets/wallets-1.webp
  images/develop/smart-contracts/wallets/wallets-10.webp
  images/develop/smart-contracts/wallets/wallets-11.webp
  images/develop/smart-contracts/wallets/wallets-2.webp
  images/develop/smart-contracts/wallets/wallets-3.webp
  images/develop/smart-contracts/wallets/wallets-4.webp
  images/develop/smart-contracts/wallets/wallets-5.webp
  images/develop/smart-contracts/wallets/wallets-6.webp
  images/develop/smart-contracts/wallets/wallets-7.webp
  images/develop/smart-contracts/wallets/wallets-8.webp
  images/develop/smart-contracts/wallets/wallets-9.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-13.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-9.webp
  images/tutorials/smart-contracts/deploy-nft/deploy-nft-13.webp
  images/tutorials/smart-contracts/deploy-nft/deploy-nft-9.webp
  images/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/create-dapp-ethers-js-1.webp
  images/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/create-dapp-ethers-js-2.webp
  images/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/create-dapp-ethers-js-3.webp
  images/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/create-dapp-ethers-js-4.webp
  images/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/create-dapp-viem-1.webp
  images/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/create-dapp-viem-2.webp
  images/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/create-dapp-viem-3.webp
  images/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/create-dapp-viem-4.webp
  js/connect-to-metamask.js
  llms.txt
  tutorials/smart-contracts/demo-aplications/deploying-uniswap-v2.md
  tutorials/smart-contracts/deploy-erc20.md
  tutorials/smart-contracts/deploy-nft.md
  tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js.md
  tutorials/smart-contracts/launch-your-first-project/create-dapp-viem.md
  tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
Labels: C2 - High, B1 - Ready to Merge, A1 - Maintenance Major

#700 [FIX] - Quick fix netwoks SC wording
  llms.txt
  polkadot-protocol/smart-contract-basics/networks.md
Labels: B0 - Needs Review, C2 - High, A1 - Maintenance Major

#695 [FIX] - hardhat quick fixes
  .snippets/code/develop/smart-contracts/dev-environments/hardhat/hardhat.config.js
  develop/smart-contracts/dev-environments/hardhat.md
  llms.txt
  tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#710 [FIX] - Cherry pick staging
  .snippets/code/develop/smart-contracts/dev-environments/hardhat/hardhat.config.js
  develop/smart-contracts/dev-environments/hardhat.md
  develop/smart-contracts/overview.md
  llms.txt
  tutorials/smart-contracts/demo-aplications/deploying-uniswap-v2.md
  tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
Labels: B0 - Needs Review, C2 - High, A1 - Maintenance Major

#709 Add note about compiler version
  llms.txt
  tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
Labels: C1 - Medium, B1 - Ready to Merge, A3 - Quick Fixes

#716 Update rust installation and local contracts node
  .snippets/code/develop/parachains/get-started/install-polkadot-sdk/termynal-2.html
  develop/parachains/install-polkadot-sdk.md
  develop/smart-contracts/local-development-node.md
  llms.txt
  variables.yml
Labels: C2 - High, B1 - Ready to Merge, A2 - Maintenance Minor

#699 SEO June
  develop/interoperability/send-messages.md
  develop/interoperability/xcm-channels.md
  develop/interoperability/xcm-config.md
  develop/networks.md
  develop/parachains/deployment/index.md
  develop/parachains/deployment/obtain-coretime.md
  develop/parachains/install-polkadot-sdk.md
  develop/toolkit/api-libraries/dedot.md
  develop/toolkit/integrations/indexers.md
  develop/toolkit/parachains/spawn-chains/zombienet/get-started.md
  infrastructure/running-a-node/setup-full-node.md
  infrastructure/running-a-node/setup-secure-wss.md
  infrastructure/running-a-validator/onboarding-and-offboarding/start-validating.md
  infrastructure/running-a-validator/operational-tasks/general-management.md
  infrastructure/running-a-validator/operational-tasks/index.md
  infrastructure/running-a-validator/operational-tasks/upgrade-your-node.md
  infrastructure/running-a-validator/requirements.md
  infrastructure/staking-mechanics/offenses-and-slashes.md
  infrastructure/staking-mechanics/rewards-payout.md
  llms.txt
  polkadot-protocol/architecture/parachains/consensus.md
  polkadot-protocol/architecture/parachains/overview.md
  polkadot-protocol/architecture/polkadot-chain/agile-coretime.md
  polkadot-protocol/architecture/polkadot-chain/overview.md
  polkadot-protocol/architecture/polkadot-chain/pos-consensus.md
  polkadot-protocol/architecture/system-chains/asset-hub.md
  polkadot-protocol/architecture/system-chains/bridge-hub.md
  polkadot-protocol/architecture/system-chains/collectives.md
  polkadot-protocol/architecture/system-chains/coretime.md
  polkadot-protocol/architecture/system-chains/overview.md
  polkadot-protocol/glossary.md
  polkadot-protocol/onchain-governance/origins-tracks.md
  polkadot-protocol/onchain-governance/overview.md
  polkadot-protocol/parachain-basics/accounts.md
  polkadot-protocol/parachain-basics/blocks-transactions-fees/fees.md
  polkadot-protocol/parachain-basics/chain-data.md
  polkadot-protocol/parachain-basics/networks.md
  tutorials/onchain-governance/fast-track-gov-proposal.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/obtain-coretime.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
  tutorials/polkadot-sdk/system-chains/asset-hub/asset-conversion.md
  tutorials/polkadot-sdk/system-chains/asset-hub/register-foreign-asset.md
  tutorials/polkadot-sdk/system-chains/asset-hub/register-local-asset.md
  tutorials/polkadot-sdk/testing/fork-live-chains.md
Labels: B1 - Ready to Merge, A2 - Maintenance Minor

#726 Update runtime-upgrades.md - tiny typo
  develop/parachains/maintenance/runtime-upgrades.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#729 [FIX] - Update SC rpc methods
  develop/smart-contracts/json-rpc-apis.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#742 Remove Duplicated Card
  develop/smart-contracts/index.md
  llms.txt
Labels: B0 - Needs Review, C0 - Low, A3 - Quick Fixes

#740 Add Warning Banner
  .snippets/text/smart-contracts/polkaVM-warning.md
  develop/smart-contracts/block-explorers/index.md
  develop/smart-contracts/connect-to-polkadot.md
  develop/smart-contracts/dev-environments/hardhat.md
  develop/smart-contracts/dev-environments/index.md
  develop/smart-contracts/dev-environments/remix.md
  develop/smart-contracts/faqs.md
  develop/smart-contracts/index.md
  develop/smart-contracts/json-rpc-apis.md
  develop/smart-contracts/libraries/ethers-js.md
  develop/smart-contracts/libraries/index.md
  develop/smart-contracts/libraries/viem.md
  develop/smart-contracts/libraries/wagmi.md
  develop/smart-contracts/libraries/web3-js.md
  develop/smart-contracts/libraries/web3-py.md
  develop/smart-contracts/local-development-node.md
  develop/smart-contracts/overview.md
  develop/smart-contracts/precompiles/index.md
  develop/smart-contracts/precompiles/interact-with-precompiles.md
  develop/smart-contracts/wallets.md
  llms.txt
  polkadot-protocol/smart-contract-basics/accounts.md
  polkadot-protocol/smart-contract-basics/blocks-transactions-fees.md
  polkadot-protocol/smart-contract-basics/evm-vs-polkavm.md
  polkadot-protocol/smart-contract-basics/index.md
  polkadot-protocol/smart-contract-basics/networks.md
  polkadot-protocol/smart-contract-basics/overview.md
  polkadot-protocol/smart-contract-basics/polkavm-design.md
  tutorials/smart-contracts/demo-aplications/deploying-uniswap-v2.md
  tutorials/smart-contracts/demo-aplications/index.md
  tutorials/smart-contracts/deploy-erc20.md
  tutorials/smart-contracts/deploy-nft.md
  tutorials/smart-contracts/index.md
  tutorials/smart-contracts/launch-your-first-project/create-contracts.md
  tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js.md
  tutorials/smart-contracts/launch-your-first-project/create-dapp-viem.md
  tutorials/smart-contracts/launch-your-first-project/index.md
  tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
Labels: B0 - Needs Review, C2 - High, A2 - Maintenance Minor

#728 Add extrinsic content archived in wiki
  llms.txt
  polkadot-protocol/parachain-basics/blocks-transactions-fees/transactions.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#739 Update faqs.md
  develop/smart-contracts/faqs.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major
