Repository polkadot-developers/polkadot-docs, pull requests merged in 2025-04, with the labels that each got.

#527 update llms script to ignore venv
  scripts/generate_llms.py
Labels: B0 - Needs Review, C2 - High, A3 - Quick Fixes

#530 Install with --locked (FIX)
  llms.txt
  tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
Labels: C2 - High, B1 - Ready to Merge, A2 - Maintenance Minor

#531 Add --locked to term
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template/compilation-output.html
  llms.txt
Labels: C2 - High, B1 - Ready to Merge, A3 - Quick Fixes

#513 Update deploy-to-testnet.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet.md
Labels: B0 - Needs Review, C1 - Medium, A3 - Quick Fixes

#514 add difficulty badges to smart contracts
  tutorials/smart-contracts/deploy-erc20.md
  tutorials/smart-contracts/deploy-nft.md
  tutorials/smart-contracts/launch-your-first-project/create-contracts.md
  tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#515 Add difficulty badges post mvp
  tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js.md
  tutorials/smart-contracts/launch-your-first-project/create-dapp-viem.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#506 Tutorial badges
  llms.txt
  tutorials/interoperability/xcm-channels/para-to-para.md
  tutorials/interoperability/xcm-channels/para-to-system.md
  tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain.md
  tutorials/onchain-governance/fast-track-gov-proposal.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/add-pallets-to-runtime.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/build-custom-pallet.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/obtain-coretime.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-benchmarking.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-unit-testing.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
  tutorials/polkadot-sdk/system-chains/asset-hub/asset-conversion.md
  tutorials/polkadot-sdk/system-chains/asset-hub/register-foreign-asset.md
  tutorials/polkadot-sdk/system-chains/asset-hub/register-local-asset.md
  tutorials/polkadot-sdk/testing/fork-live-chains.md
  tutorials/polkadot-sdk/testing/spawn-basic-chain.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#537 Update deploy-to-testnet.md (#513)
  llms.txt
  tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet.md
Labels: B1 - Ready to Merge, A3 - Quick Fixes

#548 Remove chainlink reference
  develop/toolkit/integrations/oracles.md
  llms.txt
Labels: C0 - Low, B1 - Ready to Merge, A3 - Quick Fixes

#549 Fix - hardhat guide disclaimer
  develop/smart-contracts/dev-environments/hardhat.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#542 Edit Validator Preferences
  images/infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator/set-up-a-validator-06.webp
  infrastructure/running-a-validator/onboarding-and-offboarding/start-validating.md
  llms.txt
Labels: B1 - Ready to Merge, A2 - Maintenance Minor

#544 [SC Feedback] - Remove/Rename stackexchange reference from the docs
  llms.txt
  polkadot-protocol/smart-contract-basics/overview.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#546 [SC Feedback] - Add missing PolkaVM explanation
  develop/smart-contracts/index.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#551 [SC Feedback] - Add architectural design in the polkavm design page
  llms.txt
  polkadot-protocol/smart-contract-basics/polkavm-design.md
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#553 Fix usage of variables in Hardhat tutorial
  llms.txt
  tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
Labels: C1 - Medium, B1 - Ready to Merge, A3 - Quick Fixes

#556 [SC Feedback] - Add digrams to comparing ethereum evm and polkavm
  llms.txt
  polkadot-protocol/smart-contract-basics/evm-vs-polkavm.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#559 [FIX] - Rollback json rpc api endpoint
  develop/smart-contracts/json-rpc-apis.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#560 April Semrush SEO Report
  develop/toolkit/api-libraries/py-substrate-interface.md
  llms.txt
Labels: B1 - Ready to Merge, A2 - Maintenance Minor

#561 [FIX] - dapp tutorials
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/ReadContract.tsx
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/WalletConnect.tsx
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/WriteContract.tsx
  llms.txt
  tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js.md
  tutorials/smart-contracts/launch-your-first-project/create-dapp-viem.md
  variables.yml
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#565 Fix Polkadot Relay Chain page
  llms.txt
  polkadot-protocol/architecture/index.md
  polkadot-protocol/architecture/polkadot-chain/.pages
  polkadot-protocol/architecture/polkadot-chain/index.md
Labels: C0 - Low, B1 - Ready to Merge, A3 - Quick Fixes

#573 Apply temporary fix to Set Up a Template tutorial
  llms.txt
  tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
Labels: B0 - Needs Review, C2 - High, A3 - Quick Fixes

#569 Extract tutorials to external repositories
  .snippets/code/tutorials/smart-contracts/deploy-erc20/MyToken.sol
  .snippets/code/tutorials/smart-contracts/deploy-nft/MyNFT.sol
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-contracts/Storage.sol
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/ReadContract.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/Storage.json
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/WalletConnect.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/WriteContract.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/contract.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/ethers.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/page.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/ReadContract.tsx
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/Storage.json
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/WalletConnect.tsx
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/WriteContract.tsx
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/contract.ts
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/page.tsx
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/viem.ts
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/Storage.sol
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/Storage.test.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/StorageModule.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/hardhat.config.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/interact.js
  llms.txt
  tutorials/smart-contracts/deploy-erc20.md
  tutorials/smart-contracts/deploy-nft.md
  tutorials/smart-contracts/launch-your-first-project/create-contracts.md
  tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js.md
  tutorials/smart-contracts/launch-your-first-project/create-dapp-viem.md
  tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#571 Fix typos
  develop/interoperability/intro-to-xcm.md
  llms.txt
Labels: B1 - Ready to Merge, A3 - Quick Fixes

#479 Light Client Content / Page
  develop/light-clients.md
Labels: B0 - Needs Review, A0 - New Content

#574 Add Coretime Renewal page
  develop/parachains/deployment/.pages
  develop/parachains/deployment/coretime-renewal.md
  images/develop/parachains/deployment/coretime-renewal/coretime-renewal-1.webp
  images/develop/parachains/deployment/coretime-renewal/coretime-renewal-2.webp
  images/develop/parachains/deployment/coretime-renewal/coretime-renewal-3.webp
  images/develop/parachains/deployment/coretime-renewal/coretime-renewal-4.webp
  images/develop/parachains/deployment/coretime-renewal/coretime-renewal-5.webp
  images/develop/parachains/deployment/coretime-renewal/coretime-renewal-6.webp
  images/develop/parachains/deployment/coretime-renewal/coretime-renewal-7.webp
  llms.txt
Labels: B0 - Needs Review, C2 - High, A0 - New Content

#577 Fix truncated enum line in data-encoding.md
  llms.txt
  polkadot-protocol/basics/data-encoding.md
Labels: B1 - Ready to Merge, A3 - Quick Fixes

#579 Zero to hero quick fix - snippet title
  llms.txt
  tutorials/polkadot-sdk/parachains/zero-to-hero/add-pallets-to-runtime.md
Labels: B1 - Ready to Merge, A3 - Quick Fixes

#583 Update Zero to Hero tutorial to parachain template stable2412
  .snippets/code/Cargo.lock
  .snippets/code/Cargo.toml
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallets/custom-pallet/Cargo.toml
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallets/custom-pallet/src/benchmarking.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallets/custom-pallet/src/lib.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallets/custom-pallet/src/mock.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallets/custom-pallet/src/tests.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallets/custom-pallet/src/weights.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallets/template/Cargo.toml
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallets/template/README.md
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallets/template/src/benchmarking.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallets/template/src/lib.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallets/template/src/mock.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallets/template/src/tests.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallets/template/src/weights.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/runtime/Cargo.toml
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/runtime/src/apis.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/runtime/src/benchmarks.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/runtime/src/configs/mod.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/runtime/src/configs/xcm_config.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/runtime/src/genesis_config_presets.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/runtime/src/lib.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/runtime/src/weights/block_weights.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/runtime/src/weights/extrinsic_weights.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/runtime/src/weights/paritydb_weights.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/runtime/src/weights/rocksdb_weights.rs
  llms.txt
  tutorials/polkadot-sdk/parachains/zero-to-hero/add-pallets-to-runtime.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/build-custom-pallet.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-benchmarking.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-unit-testing.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
Labels: B0 - Needs Review, C1 - Medium, A1 - Maintenance Major

#578 Precompiles docs to SC develop section
  develop/smart-contracts/.pages
  develop/smart-contracts/precompiles.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content
