Repository polkadot-developers/polkadot-docs, pull requests merged in 2025-03, with the labels that each got.

#415 Document "Web3py" for sc develop section
  .snippets/code/develop/smart-contracts/libraries/web3-py/Storage.sol
  .snippets/code/develop/smart-contracts/libraries/web3-py/connect_to_provider.py
  .snippets/code/develop/smart-contracts/libraries/web3-py/deploy.py
  .snippets/code/develop/smart-contracts/libraries/web3-py/fetch_last_block.py
  .snippets/code/develop/smart-contracts/libraries/web3-py/update_storage.py
  develop/smart-contracts/libraries/.pages
  develop/smart-contracts/libraries/web3-py.md
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#418 Develop a "Create a dapp using ethersjs" tutorial
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/ReadContract.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/Storage.json
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/WalletConnect.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/WriteContract.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/contract.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/ethers.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/page.js
  images/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/create-dapp-ethers-js-1.webp
  images/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/create-dapp-ethers-js-2.webp
  images/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/create-dapp-ethers-js-3.webp
  images/tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js/create-dapp-ethers-js-4.webp
  tutorials/smart-contracts/launch-your-first-project/.pages
  tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js.md
Labels: B0 - Needs Review, C1 - Medium, A0 - New Content

#434 Update obtain-coretime.md - minor fixes
  develop/parachains/deployment/obtain-coretime.md
  llms.txt
Labels: C0 - Low, B1 - Ready to Merge, A3 - Quick Fixes

#421 Add Subxt docs at "API Libraries" section
  .snippets/code/develop/toolkit/api-libraries/subxt/Cargo.toml
  .snippets/code/develop/toolkit/api-libraries/subxt/subxt.rs
  develop/toolkit/api-libraries/.pages
  develop/toolkit/api-libraries/subxt.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#425 Add People Chain page
  llms.txt
  polkadot-protocol/architecture/system-chains/.pages
  polkadot-protocol/architecture/system-chains/people.md
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#429 Add metamask.js
  js/connect-to-metamask.js
Labels: B1 - Ready to Merge, A3 - Quick Fixes

#444 Enhance Dependency Tracking and Issue Creation Github Action
  .github/scripts/check_dependencies.py
  .github/scripts/create_issues.py
  .github/workflows/check-dependencies.yaml
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/tx-result.md
  develop/interoperability/test-and-debug.md
  develop/interoperability/xcm-config.md
  develop/parachains/customize-parachain/add-existing-pallets.md
  develop/parachains/customize-parachain/index.md
  develop/parachains/customize-parachain/overview.md
  develop/parachains/deployment/build-deterministic-runtime.md
  develop/parachains/deployment/generate-chain-specs.md
  develop/parachains/intro-polkadot-sdk.md
  develop/parachains/maintenance/storage-migrations.md
  develop/smart-contracts/overview.md
  develop/toolkit/interoperability/asset-transfer-api/overview.md
  develop/toolkit/interoperability/asset-transfer-api/reference.md
  develop/toolkit/parachains/e2e-testing/moonwall.md
  develop/toolkit/parachains/fork-chains/chopsticks/get-started.md
  develop/toolkit/parachains/spawn-chains/zombienet/get-started.md
  infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator.md
  llms.txt
  polkadot-protocol/architecture/polkadot-chain/pos-consensus.md
  polkadot-protocol/architecture/system-chains/asset-hub.md
  polkadot-protocol/architecture/system-chains/bridge-hub.md
  polkadot-protocol/architecture/system-chains/overview.md
  polkadot-protocol/basics/blocks-transactions-fees/fees.md
  polkadot-protocol/glossary.md
  polkadot-protocol/onchain-governance/overview.md
  scripts/generate_llms.py
  tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
  tutorials/polkadot-sdk/system-chains/asset-hub/asset-conversion.md
  tutorials/polkadot-sdk/testing/spawn-basic-chain.md
  variables.yml
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#431 Fix zero-to-hero tutorial
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet/chain_spec_placeholder.json
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet/deploy-on-paseo.html
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet/key.html
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet/partial-chain-spec.json
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet/plain_chain_spec.json
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/obtain-coretime/obtain-coretime-1.html
  images/tutorials/polkadot-sdk/parachains/zero-to-hero/obtain-coretime/obtain-coretime-10.webp
  llms.txt
  tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/obtain-coretime.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
Labels: C2 - High, B1 - Ready to Merge, A2 - Maintenance Minor

#430 Create a dapp using viem tutorial
  .snippets/code/Cargo.toml
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/ReadContract.tsx
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/Storage.json
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/WalletConnect.tsx
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/WriteContract.tsx
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/contract.ts
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/page.tsx
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/viem.ts
  images/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/create-dapp-viem-1.webp
  images/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/create-dapp-viem-2.webp
  images/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/create-dapp-viem-3.webp
  images/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/create-dapp-viem-4.webp
  tutorials/smart-contracts/launch-your-first-project/.pages
  tutorials/smart-contracts/launch-your-first-project/create-dapp-viem.md
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#436 Apply feedback on build smart contracts page index
  .snippets/text/develop/smart-contracts/index/index-timeline.json
  develop/smart-contracts/index.md
  develop/smart-contracts/native-evm-contracts.md
  develop/smart-contracts/overview.md
  develop/smart-contracts/parachain-contracts.md
  develop/smart-contracts/wasm-ink.md
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#437 Add Collectives chain page
  llms.txt
  polkadot-protocol/architecture/system-chains/.pages
  polkadot-protocol/architecture/system-chains/collectives.md
  polkadot-protocol/architecture/system-chains/coretime.md
Labels: C0 - Low, B1 - Ready to Merge, A0 - New Content

#448 Apply feedback on build smart contracts connect to asset hub page
  develop/smart-contracts/connect-to-asset-hub.md
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#450 Update subxt.md
  develop/toolkit/api-libraries/subxt.md
  llms.txt
Labels: C0 - Low, B1 - Ready to Merge, A3 - Quick Fixes

#460 Create content for each blankindex page in the sc mvp content
  develop/smart-contracts/dev-environments/.pages
  develop/smart-contracts/dev-environments/foundry.md
  develop/smart-contracts/dev-environments/index.md
  develop/smart-contracts/libraries/index.md
  polkadot-protocol/smart-contract-basics/index.md
  tutorials/smart-contracts/index.md
  tutorials/smart-contracts/launch-your-first-project/index.md
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#471 Update deploy-to-testnet.md with chain onboarding note
  llms.txt
  tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet.md
Labels: C1 - Medium, B1 - Ready to Merge, A3 - Quick Fixes

#473 Semrush march report
  infrastructure/running-a-validator/index.md
  infrastructure/staking-mechanics/index.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#474 [FIX] - Web3js sunset warning
  develop/smart-contracts/libraries/web3-js.md
Labels: C0 - Low, B1 - Ready to Merge, A2 - Maintenance Minor

#475 Remove RPM Installation Instructions
  infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#476 Fix Remote Snippets in XCM Runtime APIs
  develop/interoperability/xcm-runtime-apis.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A3 - Quick Fixes

#439 Apply feedback on build smart contracts overview page
  develop/smart-contracts/overview.md
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#472 Explore and document hardhat
  .snippets/code/develop/smart-contracts/dev-environments/hardhat/hardhat.config.js
  .snippets/code/develop/smart-contracts/dev-environments/hardhat/interact.js
  .snippets/code/develop/smart-contracts/dev-environments/hardhat/lock-ignition.js
  .snippets/code/develop/smart-contracts/dev-environments/hardhat/lock-test.js
  develop/smart-contracts/dev-environments/.pages
  develop/smart-contracts/dev-environments/hardhat.md
  variables.yml
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#485 Improve tutorials create contracts page
  tutorials/smart-contracts/launch-your-first-project/create-contracts.md
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#487 Apply feedback on viem page
  .snippets/code/develop/smart-contracts/libraries/viem/chainConfig.ts
  develop/smart-contracts/libraries/viem.md
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#489 Apply feedback on JSON-RPC page
  develop/smart-contracts/json-rpc-apis.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#496 [FIX] - remove indexers folder
  develop/smart-contracts/.pages
  develop/smart-contracts/indexers/.pages
  develop/smart-contracts/indexers/index.md
  develop/smart-contracts/indexers/subsquid.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#498 fix create-contracts.md
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-contracts/Storage.sol
  tutorials/smart-contracts/launch-your-first-project/create-contracts.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#499 Create test and deploy with hardhat tutorial
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/Storage.sol
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/Storage.test.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/StorageModule.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/compilation-output.html
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/hardhat.config.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/interact-output.html
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/interact.js
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/local-deployment-output.html
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/testing-output.html
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/westend-deployment-output.html
  tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
  variables.yml
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#508 Improve tutorials create a dapp with ethersjs
  tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js.md
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#502 Add a banner on the remix ide page
  develop/smart-contracts/dev-environments/remix.md
Labels: C1 - Medium, B1 - Ready to Merge, A3 - Quick Fixes

#505 Link the content in the build section with tutorials
  develop/smart-contracts/dev-environments/hardhat.md
  develop/smart-contracts/dev-environments/remix.md
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#503 Improve deoploy nft tutorial - feedback
  tutorials/smart-contracts/deploy-nft.md
Labels: B0 - Needs Review, C1 - Medium, A1 - Maintenance Major

#518 Fix index libraries
  develop/smart-contracts/dev-environments/index.md
  develop/smart-contracts/libraries/index.md
Labels: B1 - Ready to Merge
