Repository polkadot-developers/polkadot-docs, pull requests merged in 2025-05, with the labels that each got.

#538 Add Pop CLI to Polkadot Docs – Quickstart Development Section
  .snippets/code/develop/toolkit/parachains/quickstart/pop-cli/call-chain.html
  .snippets/code/develop/toolkit/parachains/quickstart/pop-cli/install.html
  .snippets/code/develop/toolkit/parachains/quickstart/pop-cli/new-parachain.html
  develop/toolkit/parachains/.pages
  develop/toolkit/parachains/index.md
  develop/toolkit/parachains/quickstart/.pages
  develop/toolkit/parachains/quickstart/index.md
  develop/toolkit/parachains/quickstart/pop-cli.md
  images/develop/toolkit/parachains/quickstart/call-chain.gif
  images/develop/toolkit/parachains/quickstart/pop-new.gif
  llms.txt
Labels: B1 - Ready to Merge, A0 - New Content

#596 Add Pop CLI
  .snippets/code/develop/toolkit/parachains/quickstart/pop-cli/call-chain.html
  .snippets/code/develop/toolkit/parachains/quickstart/pop-cli/install.html
  .snippets/code/develop/toolkit/parachains/quickstart/pop-cli/new-parachain.html
  develop/toolkit/parachains/.pages
  develop/toolkit/parachains/index.md
  develop/toolkit/parachains/quickstart/.pages
  develop/toolkit/parachains/quickstart/index.md
  develop/toolkit/parachains/quickstart/pop-cli.md
  images/develop/toolkit/parachains/quickstart/call-chain.gif
  images/develop/toolkit/parachains/quickstart/pop-new.gif
  llms.txt
Labels: A3 - Quick Fixes

#589 Add retry to llms script
  scripts/generate_llms.py
Labels: B1 - Ready to Merge, A2 - Maintenance Minor

#605 Update hardhat.md
  develop/smart-contracts/dev-environments/hardhat.md
Labels: B1 - Ready to Merge, A3 - Quick Fixes

#608 Add page for block explorers
  develop/smart-contracts/.pages
  develop/smart-contracts/block-explorers.md
  images/develop/smart-contracts/block-explorers/block-explorers-1.webp
  images/develop/smart-contracts/block-explorers/block-explorers-2.webp
  images/develop/smart-contracts/block-explorers/block-explorers-3.webp
Labels: B0 - Needs Review, C2 - High, A0 - New Content

#606 Update Glossary
  llms.txt
  polkadot-protocol/glossary.md
Labels: C0 - Low, B1 - Ready to Merge, A2 - Maintenance Minor

#591 [Fix]- Evm vs polka vm clarification for instantiation process
  llms.txt
  polkadot-protocol/smart-contract-basics/evm-vs-polkavm.md
Labels: B1 - Ready to Merge, A2 - Maintenance Minor

#617 add difficulty badges (#515)
  tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js.md
  tutorials/smart-contracts/launch-your-first-project/create-dapp-viem.md
Labels: B0 - Needs Review, C0 - Low, A1 - Maintenance Major

#563 hardhat: fix docs according to expected kusama launch
  .snippets/code/develop/smart-contracts/dev-environments/hardhat/hardhat.config.js
  develop/smart-contracts/dev-environments/hardhat.md
Labels: B2 - Blocked

#602 feat: add dedot
  .snippets/code/develop/toolkit/api-libraries/dedot/call-runtime-apis.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/client-initialization-via-smoldot.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/client-initialization-via-ws.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/legacy-client-initialization.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/pick-chainapi-interface.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/runtime-constants.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/sign-and-send-tx-with-extension-signer.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/sign-and-send-tx-with-keyring.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/storage-queries.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/subscribe-storage-changes.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/watch-on-chain-events.ts
  develop/index.md
  develop/toolkit/api-libraries/.pages
  develop/toolkit/api-libraries/dedot.md
  llms.txt
Labels: B0 - Needs Review, A0 - New Content

#619 [FIX] - AH endpoints
  develop/smart-contracts/connect-to-asset-hub.md
  llms.txt
Labels: C2 - High, A1 - Maintenance Major, B2 - Blocked

#626 Extension of Dedot PR
  .snippets/code/develop/toolkit/api-libraries/dedot/call-runtime-apis.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/client-initialization-via-smoldot.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/client-initialization-via-ws.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/legacy-client-initialization.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/pick-chainapi-interface.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/runtime-constants.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/sign-and-send-tx-with-extension-signer.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/sign-and-send-tx-with-keyring.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/storage-queries.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/subscribe-storage-changes.ts
  .snippets/code/develop/toolkit/api-libraries/dedot/watch-on-chain-events.ts
  develop/index.md
  develop/toolkit/api-libraries/.pages
  develop/toolkit/api-libraries/dedot.md
  llms.txt
Labels: B1 - Ready to Merge, A3 - Quick Fixes

#627 [FIX] - Hardhat disclaimer in SC
  .snippets/code/develop/smart-contracts/dev-environments/hardhat/disclaimer-json-rpc-provider-alternative.js
  develop/smart-contracts/dev-environments/hardhat.md
  llms.txt
Labels: C2 - High, B1 - Ready to Merge, A1 - Maintenance Major

#624 SEO May Report fix
  .snippets/code/develop/toolkit/parachains/quickstart/pop-cli/call-chain.html
  .snippets/code/develop/toolkit/parachains/quickstart/pop-cli/new-parachain.html
  develop/parachains/customize-parachain/overview.md
  infrastructure/running-a-validator/operational-tasks/general-management.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#623 [FIX] - Update hardhat guide according to latest releases of hardhat-polkadot
  .snippets/code/develop/smart-contracts/dev-environments/hardhat/hardhat.config.js
  .snippets/code/develop/smart-contracts/dev-environments/hardhat/interact.js
  develop/smart-contracts/dev-environments/hardhat.md
  llms.txt
  variables.yml
Labels: C2 - High, B1 - Ready to Merge, A1 - Maintenance Major

#622 Add Solochain Templates and Parachain Templates subsections
  develop/parachains/customize-parachain/overview.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A3 - Quick Fixes

#586 Add section for instantiable pallets
  develop/parachains/customize-parachain/.pages
  develop/parachains/customize-parachain/add-existing-pallets.md
  develop/parachains/customize-parachain/add-pallet-instances.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#618 [FIX] - Remix pages now use Talisman
  develop/smart-contracts/connect-to-asset-hub.md
  develop/smart-contracts/dev-environments/remix.md
  images/develop/smart-contracts/connect-to-asset-hub/connect-to-asset-hub-7.webp
  images/develop/smart-contracts/connect-to-asset-hub/connect-to-asset-hub-8.webp
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-10.webp
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-11.webp
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-12.webp
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-13.webp
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-7.webp
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-8.webp
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-9.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-10.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-13.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-7.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-8.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-9.webp
  images/tutorials/smart-contracts/deploy-nft/deploy-nft-10.webp
  images/tutorials/smart-contracts/deploy-nft/deploy-nft-13.webp
  images/tutorials/smart-contracts/deploy-nft/deploy-nft-7.webp
  images/tutorials/smart-contracts/deploy-nft/deploy-nft-8.webp
  images/tutorials/smart-contracts/deploy-nft/deploy-nft-9.webp
  llms.txt
  tutorials/smart-contracts/deploy-erc20.md
  tutorials/smart-contracts/deploy-nft.md
Labels: C2 - High, B1 - Ready to Merge, A1 - Maintenance Major

#572 Rename Asset Hub to Polkadot / Westend Hub
  .snippets/code/develop/smart-contracts/dev-environments/hardhat/disclaimer-json-rpc-provider-alternative.js
  .snippets/code/develop/smart-contracts/dev-environments/hardhat/interact.js
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/fetchLastBlock.js
  .snippets/code/develop/smart-contracts/evm-toolkit/libraries/web3-js/fetchLastBlock.js
  .snippets/code/develop/smart-contracts/libraries/viem/chainConfig.ts
  .snippets/code/develop/smart-contracts/libraries/viem/createClient.ts
  .snippets/code/develop/smart-contracts/libraries/viem/createWallet.ts
  .snippets/code/develop/smart-contracts/libraries/viem/fetchLastBlock.ts
  .snippets/code/develop/smart-contracts/libraries/wagmi/page.tsx
  .snippets/code/develop/smart-contracts/libraries/wagmi/wagmi-westend-ah.ts
  .snippets/code/develop/smart-contracts/libraries/wagmi/wagmi.ts
  .snippets/code/develop/smart-contracts/libraries/web3-py/fetch_last_block.py
  .snippets/text/develop/smart-contracts/index/index-timeline.json
  develop/index.md
  develop/smart-contracts/.pages
  develop/smart-contracts/connect-to-polkadot.md
  develop/smart-contracts/connect-your-wallet.md
  develop/smart-contracts/dev-environments/hardhat.md
  develop/smart-contracts/dev-environments/remix.md
  develop/smart-contracts/index.md
  develop/smart-contracts/json-rpc-apis.md
  develop/smart-contracts/libraries/ethers-js.md
  develop/smart-contracts/libraries/viem.md
  develop/smart-contracts/libraries/wagmi.md
  develop/smart-contracts/libraries/web3-js.md
  develop/smart-contracts/libraries/web3-py.md
  develop/smart-contracts/overview.md
  llms.txt
  tutorials/smart-contracts/deploy-erc20.md
  tutorials/smart-contracts/deploy-nft.md
  tutorials/smart-contracts/launch-your-first-project/.pages
  tutorials/smart-contracts/launch-your-first-project/create-contracts.md
  tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js.md
  tutorials/smart-contracts/launch-your-first-project/create-dapp-viem.md
  tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
Labels: B0 - Needs Review, C1 - Medium, A2 - Maintenance Minor

#638 [FIX]- adding Hardhat binary configuration section and path instructions
  develop/smart-contracts/dev-environments/hardhat.md
  llms.txt
Labels: B0 - Needs Review, C2 - High, A1 - Maintenance Major

#640 Add "Verify your Contracts" page
  .snippets/code/develop/smart-contracts/contract-verification/Incrementer.sol
  develop/smart-contracts/.pages
  develop/smart-contracts/contract-verification.md
  images/develop/smart-contracts/contract-verification/contract-verification-01.webp
  images/develop/smart-contracts/contract-verification/contract-verification-02.webp
  images/develop/smart-contracts/contract-verification/contract-verification-03.webp
  images/develop/smart-contracts/contract-verification/contract-verification-04.webp
  images/develop/smart-contracts/contract-verification/contract-verification-05.webp
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#643 [FIX] - Update hardhat polkadot tutorial
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/interact-output.html
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/westend-deployment-output.html
  llms.txt
  tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
Labels: C2 - High, B1 - Ready to Merge, A1 - Maintenance Major

#639 Add elastic scaling page
  llms.txt
  polkadot-protocol/architecture/polkadot-chain/.pages
  polkadot-protocol/architecture/polkadot-chain/elastic-scaling.md
Labels: C2 - High, B1 - Ready to Merge, A0 - New Content

#468 adds timeline element to parachain zero to hero index page, updates llms
  .snippets/text/tutorials/polkadot-sdk/parachains/zero-to-hero/zero-to-hero-timeline.json
  llms.txt
  tutorials/polkadot-sdk/parachains/zero-to-hero/index.md
Labels: B1 - Ready to Merge, A1 - Maintenance Major

#644 Add Wallet page to SC
  develop/smart-contracts/.pages
  develop/smart-contracts/connect-to-polkadot.md
  develop/smart-contracts/dev-environments/hardhat.md
  develop/smart-contracts/wallets.md
  images/develop/smart-contracts/connect-to-polkadot/connect-to-polkadot-1.webp
  images/develop/smart-contracts/connect-to-polkadot/connect-to-polkadot-2.webp
  images/develop/smart-contracts/wallets/wallets-1.webp
  images/develop/smart-contracts/wallets/wallets-2.webp
  images/develop/smart-contracts/wallets/wallets-3.webp
  images/develop/smart-contracts/wallets/wallets-4.webp
  images/develop/smart-contracts/wallets/wallets-5.webp
  images/develop/smart-contracts/wallets/wallets-6.webp
  llms.txt
  tutorials/smart-contracts/deploy-erc20.md
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#654 Link fix
  develop/toolkit/parachains/light-clients.md
  llms.txt
Labels: B1 - Ready to Merge, A3 - Quick Fixes

#541 Add Uniswap V2 tutorial to SC tutorials
  .snippets/code/tutorials/smart-contracts/demo-aplications/deploying-uniswap-v2/compilation-output.html
  .snippets/code/tutorials/smart-contracts/demo-aplications/deploying-uniswap-v2/deployment-output.html
  .snippets/code/tutorials/smart-contracts/demo-aplications/deploying-uniswap-v2/testing-output.html
  llms.txt
  tutorials/smart-contracts/.pages
  tutorials/smart-contracts/demo-aplications/.pages
  tutorials/smart-contracts/demo-aplications/deploying-uniswap-v2.md
  tutorials/smart-contracts/demo-aplications/index.md
Labels: B0 - Needs Review, C2 - High, A0 - New Content

#662 [FIX] - Evm vs polka vm page update
  llms.txt
  polkadot-protocol/smart-contract-basics/evm-vs-polkavm.md
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#665 [FIX] - hardhat tutorials tags
  develop/smart-contracts/precompiles/interact-with-precompiles.md
  tutorials/smart-contracts/deploy-erc20.md
  tutorials/smart-contracts/deploy-nft.md
  tutorials/smart-contracts/launch-your-first-project/create-contracts.md
  tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#663 Add manage coretime page
  develop/parachains/deployment/.pages
  develop/parachains/deployment/manage-coretime.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#670 [Fix] - backticks uniswap tutorial
  llms.txt
  tutorials/smart-contracts/demo-aplications/deploying-uniswap-v2.md
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major
