Repository polkadot-developers/polkadot-docs, pull requests merged in 2025-08, with the labels that each got.

#856 Update GPG Key to release-team@parity.io
  infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator.md
  llms.txt
Labels: C0 - Low, B1 - Ready to Merge, A2 - Maintenance Minor

#853 [FIX] - Adding disclaimer for accounts
  develop/smart-contracts/connect-to-kusama.md
  develop/smart-contracts/connect-to-polkadot.md
  llms.txt
  polkadot-protocol/smart-contract-basics/accounts.md
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#793 Migrate transaction construction guide for integrators
  .snippets/code/develop/toolkit/integrations/signer-cli-sign-output.html
  .snippets/code/develop/toolkit/integrations/signer-cli-sign.html
  .snippets/code/develop/toolkit/integrations/signer-cli-submit-full-output.html
  .snippets/code/develop/toolkit/integrations/signer-cli-submit-output.html
  .snippets/code/develop/toolkit/integrations/subkey-generate-output.html
  .snippets/code/develop/toolkit/integrations/txwrapper-output.html
  develop/toolkit/integrations/.nav.yml
  develop/toolkit/integrations/transaction-construction.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#894 [FIX] - Update hardhat guides to `hardhat-polkadot` 1.9.0
  develop/smart-contracts/dev-environments/hardhat.md
  llms.txt
  tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#890 [FIX] - Duplicated storage migration content
  develop/parachains/maintenance/runtime-upgrades.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#875 Add guide for remote proxy implemention
  .snippets/code/develop/toolkit/parachains/remote-proxies/remote-proxy-example.js
  develop/toolkit/parachains/.nav.yml
  develop/toolkit/parachains/remote-proxies.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#804 update formatting for the tutorials section
  llms.txt
  tutorials/dapps/remark-tutorial.md
  tutorials/interoperability/index.md
  tutorials/interoperability/replay-and-dry-run-xcms.md
  tutorials/interoperability/xcm-channels/para-to-para.md
  tutorials/interoperability/xcm-channels/para-to-system.md
  tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain.md
  tutorials/onchain-governance/fast-track-gov-proposal.md
  tutorials/polkadot-sdk/index.md
  tutorials/polkadot-sdk/parachains/index.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/add-pallets-to-runtime.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/build-custom-pallet.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/obtain-coretime.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-benchmarking.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-unit-testing.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/runtime-upgrade.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
  tutorials/polkadot-sdk/system-chains/asset-hub/asset-conversion.md
  tutorials/polkadot-sdk/system-chains/asset-hub/index.md
  tutorials/polkadot-sdk/system-chains/asset-hub/register-foreign-asset.md
  tutorials/polkadot-sdk/system-chains/asset-hub/register-local-asset.md
  tutorials/polkadot-sdk/system-chains/index.md
  tutorials/polkadot-sdk/testing/fork-live-chains.md
  tutorials/polkadot-sdk/testing/index.md
  tutorials/polkadot-sdk/testing/spawn-basic-chain.md
  tutorials/smart-contracts/demo-aplications/deploying-uniswap-v2.md
  tutorials/smart-contracts/deploy-erc20.md
  tutorials/smart-contracts/deploy-nft.md
  tutorials/smart-contracts/index.md
  tutorials/smart-contracts/launch-your-first-project/create-contracts.md
  tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js.md
  tutorials/smart-contracts/launch-your-first-project/create-dapp-viem.md
  tutorials/smart-contracts/launch-your-first-project/index.md
  tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#899 add AI chatbot policy to docs
  ai-chatbot-policy.md
Labels: B1 - Ready to Merge, A0 - New Content

#887 Follow up XCM V5 guides
  .snippets/code/develop/interoperability/xcm-guides/from-apps/teleport-and-transact.ts
  .snippets/code/develop/interoperability/xcm-guides/from-apps/teleport-example.ts
  develop/interoperability/.nav.yml
  develop/interoperability/versions/.nav.yml
  develop/interoperability/versions/index.md
  develop/interoperability/versions/v5/.nav.yml
  develop/interoperability/versions/v5/asset-claimer.md
  develop/interoperability/versions/v5/fees.md
  develop/interoperability/versions/v5/index.md
  develop/interoperability/versions/v5/migration-guide.md
  develop/interoperability/versions/v5/transact.md
  develop/interoperability/versions/v5/transfers.md
  develop/interoperability/versions/v5/writing-xcm-programs.md
  develop/interoperability/xcm-channels.md
  develop/interoperability/xcm-guides/.nav.yml
  develop/interoperability/xcm-guides/from-apps/.nav.yml
  develop/interoperability/xcm-guides/from-apps/claiming-trapped-assets.md
  develop/interoperability/xcm-guides/from-apps/fees.md
  develop/interoperability/xcm-guides/from-apps/index.md
  develop/interoperability/xcm-guides/from-apps/transact.md
  develop/interoperability/xcm-guides/from-apps/transfers.md
  develop/interoperability/xcm-guides/index.md
  develop/interoperability/xcm-runtime-apis.md
  images/develop/interoperability/guides/from-apps/claiming-trapped-assets/assets-trapped-event.webp
  images/develop/interoperability/versions/v5/migration-guide/check-xcm-version.webp
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#885 Update dependencies
  develop/interoperability/test-and-debug.md
  llms.txt
  variables.yml
Labels: C0 - Low, B1 - Ready to Merge, A2 - Maintenance Minor

#908 Revert "Add content around working with non-sufficient assets (#774)"
  .snippets/code/develop/interoperability/best-practices-for-teleporting-assets/account-existence.js
  .snippets/code/develop/interoperability/best-practices-for-teleporting-assets/account-existence.ts
  .snippets/code/develop/interoperability/best-practices-for-teleporting-assets/asset-conversion-api.ts
  .snippets/code/develop/interoperability/best-practices-for-teleporting-assets/dry-run-example.ts
  .snippets/code/develop/interoperability/best-practices-for-teleporting-assets/tx-payment-api.ts
  .snippets/code/develop/interoperability/best-practices-for-teleporting-assets/xcm-delivery-fees.ts
  .snippets/code/develop/interoperability/best-practices-for-teleporting-assets/xcm-execution-fees.ts
  .snippets/code/tutorials/polkadot-sdk/system-chains/asset-hub/batch-teleport-with-dry-run.ts
  .snippets/code/tutorials/polkadot-sdk/system-chains/asset-hub/index.ts
  .snippets/code/tutorials/polkadot-sdk/system-chains/asset-hub/package.json
  .snippets/code/tutorials/polkadot-sdk/system-chains/asset-hub/papi-console-output.html
  develop/interoperability/.nav.yml
  develop/interoperability/best-practices-for-teleporting-assets.md
  images/tutorials/polkadot-sdk/system-chains/asset-hub/batch-teleport/papi-console-01.webp
  llms.txt
  polkadot-protocol/architecture/system-chains/asset-hub.md
  tutorials/polkadot-sdk/system-chains/asset-hub/.nav.yml
  tutorials/polkadot-sdk/system-chains/asset-hub/batch-teleport-assets.md
  tutorials/polkadot-sdk/system-chains/asset-hub/index.md
  tutorials/polkadot-sdk/system-chains/index.md
Labels: C1 - Medium, B1 - Ready to Merge, A3 - Quick Fixes

#907 Update wording to reflect session change
  llms-files/llms-parachains.txt
  llms-full.txt
  tutorials/interoperability/xcm-channels/para-to-system.md
Labels: C0 - Low, B1 - Ready to Merge, A3 - Quick Fixes

#883 Add Moonbeam XCM SDK reference to XCM Tools page (#862)
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/runtime/Cargo.toml
  develop/toolkit/interoperability/xcm-tools.md
  llms-files/llms-basics.txt
  llms-files/llms-dapps.txt
  llms-files/llms-infrastructure.txt
  llms-files/llms-networks.txt
  llms-files/llms-parachains.txt
  llms-files/llms-polkadot-protocol.txt
  llms-files/llms-smart-contracts.txt
  llms-files/llms-tooling.txt
  llms-full.txt
Labels: C0 - Low, B1 - Ready to Merge, A2 - Maintenance Minor

#925 [FIX] - Estimation fees line numbers
  llms-full.txt
  tutorials/interoperability/xcm-fee-estimation.md
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#919 [FIX] - Update substrate node to revive dev node
  .snippets/code/develop/smart-contracts/local-development-node/local-development-node-1.html
  develop/smart-contracts/local-development-node.md
  llms-files/llms-smart-contracts.txt
  llms-full.txt
  llms.txt
  variables.yml
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#933 [FIX] - typos across the docs
  develop/interoperability/send-messages.md
  develop/interoperability/xcm-guides/from-apps/transfers.md
  develop/networks.md
  develop/parachains/deployment/obtain-coretime.md
  develop/parachains/index.md
  develop/parachains/maintenance/runtime-metrics-monitoring.md
  develop/smart-contracts/dev-environments/remix.md
  develop/smart-contracts/faqs.md
  llms-files/llms-basics.txt
  llms-files/llms-dapps.txt
  llms-files/llms-infrastructure.txt
  llms-files/llms-networks.txt
  llms-files/llms-parachains.txt
  llms-files/llms-polkadot-protocol.txt
  llms-files/llms-smart-contracts.txt
  llms-files/llms-tooling.txt
  llms-full.txt
  polkadot-protocol/architecture/system-chains/overview.md
  polkadot-protocol/parachain-basics/accounts.md
Labels: C0 - Low, B1 - Ready to Merge, A2 - Maintenance Minor

#935 Add: ITRocket snapshot service
  infrastructure/running-a-validator/onboarding-and-offboarding/start-validating.md
  llms-files/llms-infrastructure.txt
  llms-full.txt
Labels: B1 - Ready to Merge, A2 - Maintenance Minor

#941 Revert "Add ParaSpell XCM SDK Guide"
  .snippets/code/develop/toolkit/interoperability/paraspell/dry-run-output.html
  .snippets/code/develop/toolkit/interoperability/paraspell/ed-verification-output.html
  .snippets/code/develop/toolkit/interoperability/paraspell/index.ts
  .snippets/code/develop/toolkit/interoperability/paraspell/teleport-callback-output.html
  .snippets/code/develop/toolkit/interoperability/paraspell/teleport-output.html
  .snippets/code/develop/toolkit/interoperability/paraspell/transfer-info-output.html
  develop/toolkit/interoperability/.nav.yml
  develop/toolkit/interoperability/paraspell-xcm-sdk/.nav.yml
  develop/toolkit/interoperability/paraspell-xcm-sdk/index.md
  develop/toolkit/interoperability/paraspell-xcm-sdk/teleport-from-asset-hub-to-bridge-hub.md
  llms-full.txt
  llms.txt
Labels: C2 - High, B1 - Ready to Merge, A1 - Maintenance Major
