Repository polkadot-developers/polkadot-docs, pull requests merged in 2025-09, with the labels that each got.

#942 Add ParaSpell XCM SDK page
  develop/toolkit/interoperability/.nav.yml
  develop/toolkit/interoperability/paraspell-xcm-sdk/.nav.yml
  develop/toolkit/interoperability/paraspell-xcm-sdk/index.md
  llms-full.txt
  llms.txt
Labels: C0 - Low, B1 - Ready to Merge, A0 - New Content

#995 Update dependencies
  variables.yml
Labels: C0 - Low, B1 - Ready to Merge, A2 - Maintenance Minor

#972 Update hardhat.md
  develop/smart-contracts/dev-environments/hardhat.md
  llms-files/llms-smart-contracts.txt
  llms-files/llms-tooling.txt
  llms-full.txt
Labels: B1 - Ready to Merge
