Repository polkadot-developers/polkadot-docs, pull requests merged in 2025-07, with the labels that each got.

#745 [FIX] - js library -> resolc for revive
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/compile.js
  .snippets/code/develop/smart-contracts/evm-toolkit/libraries/web3-js/compile.js
  .snippets/code/develop/smart-contracts/libraries/viem/compile.ts
  develop/smart-contracts/libraries/ethers-js.md
  develop/smart-contracts/libraries/viem.md
  develop/smart-contracts/libraries/web3-js.md
  llms.txt
  variables.yml
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#763 Update Banner Tittle
  .snippets/text/smart-contracts/polkaVM-warning.md
  llms.txt
Labels: C2 - High, B1 - Ready to Merge, A2 - Maintenance Minor

#765 Update ink! to reflect Rust instead of Wasm
  .snippets/text/develop/smart-contracts/index/index-timeline.json
  develop/smart-contracts/index.md
  develop/smart-contracts/overview.md
  llms.txt
Labels: C0 - Low, B1 - Ready to Merge, A3 - Quick Fixes

#756 [FIX] - Zero to hero tutorials
  llms.txt
  tutorials/polkadot-sdk/parachains/zero-to-hero/.pages
  tutorials/polkadot-sdk/parachains/zero-to-hero/add-pallets-to-runtime.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/build-custom-pallet.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-benchmarking.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-unit-testing.md
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#769 [Add] - connect to kusama page
  develop/smart-contracts/.pages
  develop/smart-contracts/connect-to-kusama.md
  js/connect-to-metamask.js
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#775 [FIX] - update deploy-to-testnet.md to note deprecation of `para_id` in chain specs
  llms.txt
  tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet.md
Labels: B0 - Needs Review, C1 - Medium, A2 - Maintenance Minor

#807 Remove mention of Lastic
  llms.txt
  tutorials/polkadot-sdk/parachains/zero-to-hero/obtain-coretime.md
Labels: C0 - Low, B1 - Ready to Merge, A3 - Quick Fixes

#794 [FEAT] - Add XCM precompile page
  develop/smart-contracts/precompiles/.pages
  develop/smart-contracts/precompiles/xcm-precompile.md
  images/develop/smart-contracts/precompiles/xcm-precompile/xcm-precompile-01.webp
  images/develop/smart-contracts/precompiles/xcm-precompile/xcm-precompile-02.webp
  images/develop/smart-contracts/precompiles/xcm-precompile/xcm-precompile-03.webp
  images/develop/smart-contracts/precompiles/xcm-precompile/xcm-precompile-04.webp
  images/develop/smart-contracts/precompiles/xcm-precompile/xcm-precompile-05.webp
  images/develop/smart-contracts/precompiles/xcm-precompile/xcm-precompile-06.webp
  images/develop/smart-contracts/precompiles/xcm-precompile/xcm-precompile-07.webp
  llms.txt
Labels: C2 - High, A0 - New Content

#780 [FIX] - Line numbers in dapps tutorials
  llms.txt
  scripts/generate_llms.py
  tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js.md
  tutorials/smart-contracts/launch-your-first-project/create-dapp-viem.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#832 Add SubWallet
  .DS_Store
  develop/smart-contracts/wallets.md
  images/.DS_Store
  images/develop/.DS_Store
  images/develop/smart-contracts/.DS_Store
  images/develop/smart-contracts/wallets/subwallet-01.webp
  images/develop/smart-contracts/wallets/subwallet-02.webp
  images/develop/smart-contracts/wallets/subwallet-03.webp
  images/develop/smart-contracts/wallets/subwallet-04.webp
  images/develop/smart-contracts/wallets/subwallet-PAS.webp
  llms.txt
Labels: B1 - Ready to Merge, A0 - New Content

#784 Dependency upgrade
  .nav.yml
  develop/.nav.yml
  develop/interoperability/.nav.yml
  develop/parachains/.nav.yml
  develop/parachains/customize-parachain/.nav.yml
  develop/parachains/deployment/.nav.yml
  develop/parachains/maintenance/.nav.yml
  develop/parachains/testing/.nav.yml
  develop/smart-contracts/.nav.yml
  develop/smart-contracts/block-explorers/.nav.yml
  develop/smart-contracts/dev-environments/.nav.yml
  develop/smart-contracts/dev-environments/hardhat.md
  develop/smart-contracts/libraries/.nav.yml
  develop/smart-contracts/precompiles/.nav.yml
  develop/toolkit/.nav.yml
  develop/toolkit/api-libraries/.nav.yml
  develop/toolkit/integrations/.nav.yml
  develop/toolkit/interoperability/.nav.yml
  develop/toolkit/interoperability/asset-transfer-api/.nav.yml
  develop/toolkit/parachains/.nav.yml
  develop/toolkit/parachains/e2e-testing/.nav.yml
  develop/toolkit/parachains/fork-chains/.nav.yml
  develop/toolkit/parachains/fork-chains/chopsticks/.nav.yml
  develop/toolkit/parachains/quickstart/.nav.yml
  develop/toolkit/parachains/spawn-chains/.nav.yml
  develop/toolkit/parachains/spawn-chains/zombienet/.nav.yml
  get-support/.nav.yml
  infrastructure/.nav.yml
  infrastructure/running-a-node/.nav.yml
  infrastructure/running-a-validator/.nav.yml
  infrastructure/running-a-validator/onboarding-and-offboarding/.nav.yml
  infrastructure/running-a-validator/operational-tasks/.nav.yml
  infrastructure/staking-mechanics/.nav.yml
  llms.txt
  polkadot-protocol/.nav.yml
  polkadot-protocol/architecture/.nav.yml
  polkadot-protocol/architecture/parachains/.nav.yml
  polkadot-protocol/architecture/polkadot-chain/.nav.yml
  polkadot-protocol/architecture/system-chains/.nav.yml
  polkadot-protocol/onchain-governance/.nav.yml
  polkadot-protocol/parachain-basics/.nav.yml
  polkadot-protocol/parachain-basics/blocks-transactions-fees/.nav.yml
  polkadot-protocol/smart-contract-basics/.nav.yml
  tutorials/.nav.yml
  tutorials/dapps/.nav.yml
  tutorials/interoperability/.nav.yml
  tutorials/interoperability/xcm-channels/.nav.yml
  tutorials/interoperability/xcm-transfers/.nav.yml
  tutorials/onchain-governance/.nav.yml
  tutorials/onchain-governance/fast-track-gov-proposal.md
  tutorials/polkadot-sdk/.nav.yml
  tutorials/polkadot-sdk/parachains/.nav.yml
  tutorials/polkadot-sdk/parachains/zero-to-hero/.nav.yml
  tutorials/polkadot-sdk/system-chains/.nav.yml
  tutorials/polkadot-sdk/system-chains/asset-hub/.nav.yml
  tutorials/polkadot-sdk/testing/.nav.yml
  tutorials/smart-contracts/.nav.yml
  tutorials/smart-contracts/demo-aplications/.nav.yml
  tutorials/smart-contracts/launch-your-first-project/.nav.yml
Labels: B1 - Ready to Merge, A1 - Maintenance Major

#835 fix: 404s
  develop/parachains/customize-parachain/overview.md
  develop/smart-contracts/precompiles/xcm-precompile.md
  llms.txt
  polkadot-protocol/smart-contract-basics/accounts.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#845 Adding pr label checker
  .github/workflows/check-pr-labels.yml
Labels: B0 - Needs Review, C1 - Medium, A1 - Maintenance Major

#851 [Fix] - typo
  .github/workflows/check-pr-labels.yml
  llms.txt
  tutorials/interoperability/xcm-transfers/index.md
Labels: C0 - Low, B1 - Ready to Merge, A2 - Maintenance Minor

#788 Add asynchronous backing guide
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/Cargo.toml
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/apis-01.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/apis-02.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/genesis_config_preset_snippet.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/lib-01.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/lib-02.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/lib-03.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/lib-04.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/lib-05.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/lib-06.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/lib-07.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/lib-08.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/lib-09.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/lib-10.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/lib-11.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/lib-12.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/service-01.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/service-02.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/service-03.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/service-04.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/service-05.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/service-06.rs
  .snippets/code/develop/parachains/maintenance/configure-asynchronous-backing/service-07.rs
  develop/parachains/maintenance/.nav.yml
  develop/parachains/maintenance/configure-asynchronous-backing.md
  llms.txt
Labels: B1 - Ready to Merge, A0 - New Content

#837 Remove .DS_Store files
  .DS_Store
  .gitignore
  images/.DS_Store
  images/develop/.DS_Store
  images/develop/smart-contracts/.DS_Store
Labels: C0 - Low, B1 - Ready to Merge, A3 - Quick Fixes

#840 [FIX] - Add chopsticks replay and dry-run XCMs tutorial
  .snippets/code/tutorials/interoperability/replay-and-dry-run-xcms/dry-run-call.ts
  .snippets/code/tutorials/interoperability/replay-and-dry-run-xcms/dry-run-failure.html
  .snippets/code/tutorials/interoperability/replay-and-dry-run-xcms/dry-run-success.html
  .snippets/code/tutorials/interoperability/replay-and-dry-run-xcms/launch-chopsticks.html
  .snippets/code/tutorials/interoperability/replay-and-dry-run-xcms/replay-xcm-result.html
  .snippets/code/tutorials/interoperability/replay-and-dry-run-xcms/replay-xcm.ts
  llms.txt
  tutorials/interoperability/.nav.yml
  tutorials/interoperability/replay-and-dry-run-xcms.md
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#848 Update Penalties by Offenses
  infrastructure/staking-mechanics/offenses-and-slashes.md
  llms.txt
Labels: C0 - Low, B1 - Ready to Merge, A2 - Maintenance Minor
