Repository polkadot-developers/polkadot-docs, pull requests merged in 2025-10, with the labels that each got.

#1007 Latest Node recommended, fixed indentation
  develop/smart-contracts/dev-environments/hardhat.md
  llms-files/llms-smart-contracts.txt
  llms-files/llms-tooling.txt
  llms-full.txt
Labels: C0 - Low, B1 - Ready to Merge, A2 - Maintenance Minor

#944 Add Polkadart to tooling section
  develop/toolkit/api-libraries/.nav.yml
  develop/toolkit/api-libraries/polkadart.md
  llms-files/llms-dapps.txt
  llms-files/llms-tooling.txt
  llms-full.txt
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#1003 Update .nav.yml
  develop/toolkit/interoperability/.nav.yml
Labels: B1 - Ready to Merge

#1006 Update Rust setup instructions in template guide
  llms-files/llms-basics.txt
  llms-files/llms-dapps.txt
  llms-files/llms-infrastructure.txt
  llms-files/llms-networks.txt
  llms-files/llms-parachains.txt
  llms-files/llms-polkadot-protocol.txt
  llms-files/llms-smart-contracts.txt
  llms-files/llms-tooling.txt
  llms-full.txt
  tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
Labels: C0 - Low, B1 - Ready to Merge, A2 - Maintenance Minor

#979 Update validator onboarding images and documentation
  images/infrastructure/running-a-validator/onboarding-and-offboarding/start-validating/start-validating-01.webp
  images/infrastructure/running-a-validator/onboarding-and-offboarding/start-validating/start-validating-02.webp
  images/infrastructure/running-a-validator/onboarding-and-offboarding/start-validating/start-validating-03.webp
  images/infrastructure/running-a-validator/onboarding-and-offboarding/start-validating/start-validating-04.webp
  images/infrastructure/running-a-validator/onboarding-and-offboarding/start-validating/start-validating-06.webp
  infrastructure/running-a-validator/onboarding-and-offboarding/start-validating.md
  llms-files/llms-dapps.txt
  llms-files/llms-infrastructure.txt
  llms-files/llms-tooling.txt
  llms-full.txt
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#1017 Add Faucets page (new IA)
  images/smart-contracts/faucets/faucets-1.webp
  images/smart-contracts/faucets/faucets-2.webp
  llms-files/llms-smart-contracts.txt
  llms-full.txt
  llms.txt
  smart-contracts/faucets.md
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major
