Repository polkadot-developers/polkadot-docs, pull requests merged in 2025-01, with the labels that each got.

#268 Create mermaid diagram for Coretime
  polkadot-protocol/architecture/polkadot-chain/agile-coretime.md
Labels: documentation

#256 [FIX] - Adding `npm install` to contributing.md
  .CONTRIBUTING.md
Labels: B0 - Needs Review

#289 Add note about prefunded accounts
  tutorials/polkadot-sdk/parachains/zero-to-hero/add-pallets-to-runtime.md
Labels: C1 - Medium, B1 - Ready to be Merged, A3 - Quick Fixes

#257 Improve Set Up Validator
  infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator.md
  variables.yml
Labels: C1 - Medium, B1 - Ready to be Merged, A2 - Maintenance Minor

#304 Site health improvements - january report
  .snippets/code/tutorials/polkadot-sdk/testing/spawn-basic-chain/spawn-network-terminal-01.html
  develop/parachains/testing/setup.md
  develop/toolkit/parachains/spawn-chains/zombienet/get-started.md
Labels: C1 - Medium, B1 - Ready to be Merged, A2 - Maintenance Minor

#231 [FIX] - remote snippets
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/asset-transfer-type.md
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/ca-fn-signature.ts
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/constructed-format.md
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/ctt-fn-signature.ts
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/de-fn-signature.ts
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/ffi-fn-signature.ts
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/format.ts
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/transfer-arg-opts.md
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/tx-result.md
  .snippets/code/polkadot-protocol/basics/accounts/account-data-structure-1.rs
  .snippets/code/polkadot-protocol/basics/accounts/account-data-structure-2.rs
  develop/interoperability/test-and-debug.md
  develop/interoperability/xcm-config.md
  develop/parachains/customize-parachain/add-existing-pallets.md
  develop/parachains/customize-parachain/index.md
  develop/parachains/customize-parachain/overview.md
  develop/parachains/deployment/generate-chain-specs.md
  develop/parachains/intro-polkadot-sdk.md
  develop/parachains/maintenance/storage-migrations.md
  develop/smart-contracts/overview.md
  develop/toolkit/interoperability/asset-transfer-api/reference.md
  infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator.md
  polkadot-protocol/architecture/polkadot-chain/pos-consensus.md
  polkadot-protocol/architecture/system-chains/asset-hub.md
  polkadot-protocol/architecture/system-chains/bridge-hub.md
  polkadot-protocol/architecture/system-chains/overview.md
  polkadot-protocol/basics/accounts.md
  polkadot-protocol/basics/blocks-transactions-fees/fees.md
  polkadot-protocol/glossary.md
  polkadot-protocol/onchain-governance/overview.md
  tutorials/polkadot-sdk/system-chains/asset-hub/asset-conversion.md
  variables.yml
Labels: C1 - Medium, B1 - Ready to be Merged, A1 - Maintenance Major

#280 Create mermaid diagram for FRAME section
  develop/parachains/intro-polkadot-sdk.md
Labels: B0 - Needs Review, C0 - Low, A0 - New Content

#309 Document "Remix IDE" for asset hub smart contracts
  .CONTRIBUTING.md
  .github/CODEOWNERS
  .github/env
  .github/workflows/checks.yml
  .github/workflows/reusable-preflight.yml
  .snippets/code/README.md
  .snippets/code/develop/smart-contracts/evm-toolkit/dev-environments/remix/Counter.sol
  .snippets/code/develop/smart-contracts/native-evm-contracts/ether-js-server-connection.js
  .snippets/code/rust-toolchain.toml
  .snippets/code/tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain/reserve-backed-transfer.js
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/build-custom-pallet/src/lib.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/build-custom-pallet/tests/integration_tests.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-benchmarking/benchmarking.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-benchmarking/benchmarks.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-benchmarking/lib.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-benchmarking/mock.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-benchmarking/mod.rs
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-benchmarking/pallet-cargo.toml
  .snippets/code/tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-benchmarking/runtime-cargo.toml
  .snippets/code/tutorials/polkadot-sdk/testing/spawn-basic-chain/connect-to-alice-01.js
  develop/smart-contracts/.pages
  develop/smart-contracts/evm-toolkit/.pages
  develop/smart-contracts/evm-toolkit/dev-environment/index.md
  develop/smart-contracts/evm-toolkit/dev-environments/.pages
  develop/smart-contracts/evm-toolkit/dev-environments/foundry.md
  develop/smart-contracts/evm-toolkit/dev-environments/hardhat.md
  develop/smart-contracts/evm-toolkit/dev-environments/index.md
  develop/smart-contracts/evm-toolkit/dev-environments/remix.md
  develop/smart-contracts/evm-toolkit/index.md
  develop/smart-contracts/evm/.pages
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-1.webp
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-10.webp
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-2.webp
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-3.webp
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-4.webp
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-5.webp
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-6.webp
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-7.webp
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-8.webp
  images/develop/smart-contracts/evm-toolkit/dev-environments/remix/remix-9.webp
  polkadot-protocol/architecture/polkadot-chain/pos-consensus.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/.pages
  tutorials/polkadot-sdk/parachains/zero-to-hero/build-custom-pallet.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-benchmarking.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-unit-testing.md
Labels: C1 - Medium, B1 - Ready to be Merged, A0 - New Content

#319 develop/interop messaging admonition updates
  develop/index.md
  develop/interoperability/send-messages.md
  develop/interoperability/test-and-debug.md
Labels: B1 - Ready to be Merged, A2 - Maintenance Minor

#315 Add Moonwall
  .snippets/code/develop/toolkit/parachains/e2e-testing/moonwall/init-moonwall.config.json
  .snippets/code/develop/toolkit/parachains/e2e-testing/moonwall/init.html
  .snippets/code/develop/toolkit/parachains/e2e-testing/moonwall/moonwall.config.json
  .snippets/code/develop/toolkit/parachains/e2e-testing/moonwall/output.html
  .snippets/code/develop/toolkit/parachains/e2e-testing/moonwall/test1.ts
  develop/toolkit/parachains/.pages
  develop/toolkit/parachains/e2e-testing/.pages
  develop/toolkit/parachains/e2e-testing/index.md
  develop/toolkit/parachains/e2e-testing/moonwall.md
  develop/toolkit/parachains/index.md
  variables.yml
Labels: C1 - Medium, B1 - Ready to be Merged, A0 - New Content

#305 Update page Develop -> Testing -> Benchmarking
  .snippets/code/develop/parachains/testing/benchmarking/benchmark-output.html
  .snippets/code/develop/parachains/testing/benchmarking/runtime-cargo.toml
  .snippets/code/develop/parachains/testing/benchmarking/runtime-pallet-config.rs
  .snippets/code/develop/parachains/testing/benchmarking/weight-config.rs
  develop/parachains/testing/benchmarking.md
Labels: C1 - Medium, B1 - Ready to be Merged, A2 - Maintenance Minor

#295 Document Ether.js for asset hub smart contracts
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/Storage.sol
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/checkStorage.js
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/compile.js
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/connectToProvider.js
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/deploy.js
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/fetchLastBlock.js
  develop/smart-contracts/.pages
  develop/smart-contracts/evm-toolkit/index.md
  develop/smart-contracts/evm-toolkit/libraries/.pages
  develop/smart-contracts/evm-toolkit/libraries/ether-js.md
  develop/smart-contracts/evm-toolkit/libraries/ethers-js.md
  develop/smart-contracts/evm-toolkit/libraries/index.md
Labels: C1 - Medium, B1 - Ready to be Merged, A0 - New Content

#331 protocol/gov and glossary admos
  polkadot-protocol/glossary.md
  polkadot-protocol/onchain-governance/origins-tracks.md
Labels: B1 - Ready to be Merged, A2 - Maintenance Minor
