Repository polkadot-developers/polkadot-docs, pull requests merged in 2025-02, with the labels that each got.

#336 Add XCM Runtime APIs to Develop -> Interoperability
  .snippets/code/develop/interoperability/xcm-runtime-apis/call-example-output.html
  .snippets/code/develop/interoperability/xcm-runtime-apis/call-example.js
  .snippets/code/develop/interoperability/xcm-runtime-apis/query-assets-output.html
  .snippets/code/develop/interoperability/xcm-runtime-apis/query-assets.js
  .snippets/code/develop/interoperability/xcm-runtime-apis/query-delivery-fees-output.html
  .snippets/code/develop/interoperability/xcm-runtime-apis/query-delivery-fees.js
  .snippets/code/develop/interoperability/xcm-runtime-apis/query-weight-to-fee-output.html
  .snippets/code/develop/interoperability/xcm-runtime-apis/query-weight-to-fee.js
  .snippets/code/develop/interoperability/xcm-runtime-apis/query-xcm-weight-output.html
  .snippets/code/develop/interoperability/xcm-runtime-apis/query-xcm-weight.js
  .snippets/code/develop/interoperability/xcm-runtime-apis/xcm-example-output.html
  .snippets/code/develop/interoperability/xcm-runtime-apis/xcm-example.js
  develop/interoperability/.pages
  develop/interoperability/xcm-runtime-apis.md
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#339 Refactor Develop -> Interoperabiity -> Testing and Debugging
  develop/interoperability/test-and-debug.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#351 Fix: Discrepancy in validators minimum requirements
  infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator.md
  infrastructure/running-a-validator/requirements.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#348 clean up the general management docs
  infrastructure/running-a-validator/operational-tasks/general-management.md
Labels: C0 - Low, B1 - Ready to Merge, A2 - Maintenance Minor

#320 develop/parachains messaging admo updates
  develop/parachains/customize-parachain/add-existing-pallets.md
  develop/parachains/customize-parachain/make-custom-pallet.md
  develop/parachains/customize-parachain/overview.md
  develop/parachains/intro-polkadot-sdk.md
Labels: B1 - Ready to Merge, A2 - Maintenance Minor

#321 develop/parachains testing, deployment, maintenance admo
  develop/parachains/deployment/generate-chain-specs.md
  develop/parachains/deployment/index.md
  develop/parachains/testing/benchmarking.md
  develop/parachains/testing/mock-runtime.md
Labels: B1 - Ready to Merge, A2 - Maintenance Minor

#322 updates admos for dev/smart contracts
  develop/smart-contracts/index.md
  develop/smart-contracts/overview.md
  develop/smart-contracts/wasm-ink.md
Labels: B1 - Ready to Merge, A2 - Maintenance Minor

#329 protocol/architecture updates use of admos for all pages in section
  polkadot-protocol/architecture/parachains/overview.md
  polkadot-protocol/architecture/polkadot-chain/overview.md
  polkadot-protocol/architecture/polkadot-chain/pos-consensus.md
  polkadot-protocol/architecture/system-chains/bridge-hub.md
  polkadot-protocol/architecture/system-chains/coretime.md
  polkadot-protocol/architecture/system-chains/overview.md
Labels: B1 - Ready to Merge, A2 - Maintenance Minor

#332 tutorial admonition updates
  tutorials/polkadot-sdk/parachains/zero-to-hero/add-pallets-to-runtime.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/build-custom-pallet.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/index.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/obtain-coretime.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-benchmarking.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-unit-testing.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
  tutorials/polkadot-sdk/system-chains/asset-hub/asset-conversion.md
  tutorials/polkadot-sdk/system-chains/asset-hub/register-foreign-asset.md
  tutorials/polkadot-sdk/system-chains/asset-hub/register-local-asset.md
  tutorials/polkadot-sdk/testing/fork-live-chains.md
Labels: B1 - Ready to Merge, A2 - Maintenance Minor

#330 protocol/basics admo updates
  polkadot-protocol/basics/accounts.md
  polkadot-protocol/basics/blocks-transactions-fees/blocks.md
  polkadot-protocol/basics/blocks-transactions-fees/fees.md
  polkadot-protocol/basics/blocks-transactions-fees/transactions.md
  polkadot-protocol/basics/chain-data.md
  polkadot-protocol/basics/cryptography.md
  polkadot-protocol/basics/data-encoding.md
  polkadot-protocol/basics/randomness.md
Labels: B1 - Ready to Merge, A2 - Maintenance Minor

#349 Create "JSON-RPC APIs (Eth Compatibility)" page
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/checkStorage.js
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/compile.js
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/deploy.js
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/fetchLastBlock.js
  develop/smart-contracts/.pages
  develop/smart-contracts/json-rpc-apis.md
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#371 update srtool to latest version
  develop/parachains/deployment/build-deterministic-runtime.md
  variables.yml
Labels: C0 - Low, B1 - Ready to Merge, A2 - Maintenance Minor

#344 Add "Deploy an ERC20" with remix tutorial
  .snippets/code/tutorials/smart-contracts/deploy-erc20/MyToken.sol
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-1.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-10.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-11.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-12.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-13.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-2.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-3.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-4.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-5.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-6.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-7.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-8.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-9.webp
  tutorials/smart-contracts/.pages
  tutorials/smart-contracts/deploy-erc20.md
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#326 updates admonitions for all pages in Infra section
  .snippets/code/infrastructure/running-a-validator/onboarding-and-offboarding/set-up-a-validator/terminal-output-03.html
  images/infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator/set-up-a-validator-01.webp
  images/infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator/set-up-a-validator-02.webp
  images/infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator/set-up-a-validator-03.webp
  images/infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator/set-up-a-validator-04.webp
  images/infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator/set-up-a-validator-05.webp
  images/infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator/set-up-a-validator-06.webp
  infrastructure/running-a-node/setup-bootnode.md
  infrastructure/running-a-node/setup-full-node.md
  infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator.md
  infrastructure/running-a-validator/operational-tasks/general-management.md
  infrastructure/running-a-validator/requirements.md
  infrastructure/staking-mechanics/offenses-and-slashes.md
  infrastructure/staking-mechanics/rewards-payout.md
Labels: A2 - Maintenance Minor

#368 Adds LLMS Flow
  .github/workflows/check-llms.yml
  infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator.md
  llms.txt
  scripts/generate_llms.py
Labels: B1 - Ready to Merge, A1 - Maintenance Major

#384 Improved wording for era points explanation
  infrastructure/staking-mechanics/rewards-payout.md
  llms.txt
Labels: B0 - Needs Review, C0 - Low, A3 - Quick Fixes

#386 Semrush Audit February
  develop/interoperability/xcm-runtime-apis.md
  llms.txt
Labels: C2 - High, B1 - Ready to Merge, A3 - Quick Fixes

#385 Create "Accounts" page in sc basics section
  polkadot-protocol/.pages
  polkadot-protocol/smart-contract-basics/.pages
  polkadot-protocol/smart-contract-basics/accounts.md
  polkadot-protocol/smart-contract-basics/evm-vs-polkavm.md
  polkadot-protocol/smart-contract-basics/index.md
  polkadot-protocol/smart-contract-basics/overview.md
  polkadot-protocol/smart-contract-basics/polkavm-design.md
  polkadot-protocol/smart-contracts-basics/.pages
  polkadot-protocol/smart-contracts-basics/index.md
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#383 Update the layout of the JSON RPC page
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/checkStorage.js
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/compile.js
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/deploy.js
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/fetchLastBlock.js
  .snippets/code/develop/smart-contracts/native-evm-contracts/ether-js-server-connection.js
  .snippets/code/tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain/reserve-backed-transfer.js
  .snippets/code/tutorials/polkadot-sdk/testing/spawn-basic-chain/connect-to-alice-01.js
  develop/smart-contracts/json-rpc-apis.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#379 update asset-transfer-api to latest version
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/transfer-arg-opts.md
  .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/tx-result.md
  develop/toolkit/interoperability/asset-transfer-api/reference.md
  llms.txt
  variables.yml
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#377 100 is now 5000 PAS
  tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet.md
Labels: C0 - Low, B1 - Ready to Merge, A3 - Quick Fixes

#365 Document "How to Connect to Asset Hub"
  develop/smart-contracts/.pages
  develop/smart-contracts/connect-to-asset-hub.md
  images/develop/smart-contracts/connect-to-asset-hub/connect-to-asset-hub-1.webp
  images/develop/smart-contracts/connect-to-asset-hub/connect-to-asset-hub-2.webp
  images/develop/smart-contracts/connect-to-asset-hub/connect-to-asset-hub-3.webp
  images/develop/smart-contracts/connect-to-asset-hub/connect-to-asset-hub-4.webp
  images/develop/smart-contracts/connect-to-asset-hub/connect-to-asset-hub-5.webp
  images/develop/smart-contracts/connect-to-asset-hub/connect-to-asset-hub-6.webp
  js/connect-to-metamask.js
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#358 Document "Web3.js" for asset hub smart contracts
  .snippets/code/develop/smart-contracts/evm-toolkit/libraries/web3-js/Storage.sol
  .snippets/code/develop/smart-contracts/evm-toolkit/libraries/web3-js/compile.js
  .snippets/code/develop/smart-contracts/evm-toolkit/libraries/web3-js/connectToProvider.js
  .snippets/code/develop/smart-contracts/evm-toolkit/libraries/web3-js/deploy.js
  .snippets/code/develop/smart-contracts/evm-toolkit/libraries/web3-js/fetchLastBlock.js
  .snippets/code/develop/smart-contracts/evm-toolkit/libraries/web3-js/updateStorage.js
  develop/smart-contracts/libraries/web3-js.md
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#393 Update Chopsticks and Zombienet versions
  llms.txt
  tutorials/polkadot-sdk/testing/spawn-basic-chain.md
  variables.yml
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#398 Modify the titles to be more action-oriented
  llms.txt
  tutorials/interoperability/xcm-channels/para-to-para.md
  tutorials/interoperability/xcm-channels/para-to-system.md
  tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain.md
  tutorials/onchain-governance/fast-track-gov-proposal.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/obtain-coretime.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-unit-testing.md
  tutorials/polkadot-sdk/system-chains/asset-hub/asset-conversion.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#380 Create "Networks" page in sc basics
  polkadot-protocol/smart-contract-basics/.pages
  polkadot-protocol/smart-contract-basics/networks.md
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#394 [FIX] - Pre-commit hook over staged files
  .husky/pre-commit
  llms.txt
Labels: C0 - Low, B1 - Ready to Merge, A3 - Quick Fixes

#376 Create "EVM vs PolkaVM" page in sc basics section
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/checkStorage.js
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/compile.js
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/deploy.js
  .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/fetchLastBlock.js
  .snippets/code/develop/smart-contracts/native-evm-contracts/ether-js-server-connection.js
  .snippets/code/tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain/reserve-backed-transfer.js
  .snippets/code/tutorials/polkadot-sdk/testing/spawn-basic-chain/connect-to-alice-01.js
  polkadot-protocol/smart-contract-basics/evm-vs-polkavm.md
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#360 Create "PolkaVM Design" page in SC basics section
  polkadot-protocol/architecture/polkadot-chain/overview.md
  polkadot-protocol/parachain-basics/chain-data.md
  polkadot-protocol/smart-contract-basics/polkavm-design.md
  tutorials/polkadot-sdk/parachains/zero-to-hero/add-pallets-to-runtime.md
Labels: B0 - Needs Review, C1 - Medium, A0 - New Content

#402 Fixes LLMS Script
  llms.txt
  scripts/generate_llms.py
Labels: B0 - Needs Review, A3 - Quick Fixes

#392 Create "Blocks transactions and fees" page in sc basics section
  polkadot-protocol/smart-contract-basics/.pages
  polkadot-protocol/smart-contract-basics/blocks-transactions-fees.md
Labels: B0 - Needs Review, C1 - Medium, A0 - New Content

#409 Create "Create Contract" tutorial
  .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-contracts/Storage.sol
  tutorials/smart-contracts/launch-your-first-project/create-contracts.md
Labels: C1 - Medium, B1 - Ready to Merge, A0 - New Content

#411 [FIX] - Update open zeppelin contract wizard references
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-10.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-11.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-12.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-13.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-14.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-2.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-3.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-4.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-5.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-6.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-7.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-8.webp
  images/tutorials/smart-contracts/deploy-erc20/deploy-erc20-9.webp
  images/tutorials/smart-contracts/deploy-nft/deploy-nft-2.webp
  tutorials/smart-contracts/deploy-erc20.md
  tutorials/smart-contracts/deploy-nft.md
Labels: C1 - Medium, B1 - Ready to Merge, A2 - Maintenance Minor

#369 Add node and runtime page
  llms.txt
  polkadot-protocol/basics/.pages
  polkadot-protocol/basics/node-and-runtime.md
Labels: C0 - Low, B1 - Ready to Merge, A0 - New Content

#404 Split Set Up a Validator page in multiple pages and add improve Key Management docs
  .snippets/code/infrastructure/running-a-validator/onboarding-and-offboarding/key-management/subkey-generate.html
  images/infrastructure/running-a-validator/onboarding-and-offboarding/key-management/key-management-1.webp
  images/infrastructure/running-a-validator/onboarding-and-offboarding/key-management/key-management-2.webp
  infrastructure/running-a-validator/onboarding-and-offboarding/.pages
  infrastructure/running-a-validator/onboarding-and-offboarding/key-management.md
  infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator.md
  infrastructure/running-a-validator/onboarding-and-offboarding/start-validating.md
  llms.txt
Labels: C1 - Medium, B1 - Ready to Merge, A1 - Maintenance Major

#396 Add workflow to detect url changes
  .github/workflows/check-url-changes.yml
Labels: C2 - High, B1 - Ready to Merge, A1 - Maintenance Major
